// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Beyond Vision",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Beyond Vision",
            targets: ["AppModule"],
            bundleIdentifier: "in.swastik.beyondVision",
            teamIdentifier: "73B8W4ZN6V",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .photoLibrary(purposeString: "Beyond Vision lets you choose your own photos to explore through touch and haptics."),
                .photoLibraryAdd(purposeString: "Beyond Vision needs access to save images you explore."),
                .camera(purposeString: "Beyond Vision uses the camera so you can feel the objects around you in real time.")
            ],
            appCategory: .utilities
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Resources/ObjectDetector.mlmodelc")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)